language: haskell

ghc:
    # - 7.8
    - 7.6

before_install:
    - cabal install cabal-install --constraint='cabal-install >= 1.20'
    - cabal --version
    - cabal install cpphs
    - cabal install command-qq
    - git clone https://github.com/supki/.dotfiles

script:
    - cabal install --enable-tests
    - cabal sdist
    - ghc -O example/datetime.hs
    - ghc -O example/aggregation.hs
    - ghc -O .dotfiles/core/pakej.hs
    - pakej --init
    - pakej --recompile
