language: haskell

ghc:
    - 7.8
    - 7.6

before_install:
    - cabal install cabal-install --constraint='cabal-install >= 1.20' --constraint='transformers < 0.4'
    - export PATH="$HOME/.cabal/bin:$PATH"
    - hash -r
    - cabal --version
    - cabal install command-qq
    - git clone https://github.com/supki/.dotfiles

install:
    - cabal install --enable-tests --force-reinstall

script:
    - cabal sdist
    - ghc -O example/datetime.hs
    - ghc -O example/aggregation.hs
    - ghc -O .dotfiles/core/pakej.hs
    - pakej --init
    - pakej --recompile
